[package]
name = "mccabre"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
owo-colors = "4.2.3"
anyhow = "1.0"
serde_json = "1.0"
mccabre-core = { path = "../core" }
